version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    allow:
      # Allow updates for @graphql-mesh related packages
      - dependency-name: '@graphql-mesh/*'
