version: '3'

services:
  gql-mesh-database:
    image: mysql:5.7.25
    container_name: gql-mesh-database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - /var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
